borg-passphrase: ENC[AES256_GCM,data:F/nb/Oi6wnOLQUxKcFJKgKmAVeKGFBPRkobYQgXnzRxlm7/3LcTkv5VXFSQ=,iv:AbZwZ9hJRqJnw0C0aSLq2iYmieuFdnQQbDTfbPZnrS0=,tag:yAlyKc5OmJ8aL9XBnovdmg==,type:str]
borg-repo-env: ENC[AES256_GCM,data:EapCZkKnNcdL+CIGhKKQhmfxIqMu3NpeItyfp/Tr8HujlGtKweErnAvM/sXx70MSrNYXI2x4zwhn4A==,iv:BH3Bi5a83vb7TXw9drhZTNSqifXfbFOVm3BTxxel0Hc=,tag:2bvUh7Unuokp/1fU7DXZzQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlSU1aSTNNblloRVFCM0ZK
            NGc0M0RYdkliaTRhRm5sZzlmUFdaYnV5K0UwClFjeGQyZmJ5WnE3YzNsWUpQOHlh
            cWo1NUdHWHQ2MVVLanUrSjNzditXTkkKLS0tIG11T1JnOEo5UlQ1MUIrcXZJS1Jm
            ZTRlblVteWRZK1E2bjdScGI2RDlhOVEKmNG50SllycTdt1pnqIKCiW8fI5xYIAdW
            Mydc0Se1sV4kO3GF+YhSDsH79/5QucQnPn85zXJyFzKnvqfQd9FCYA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17r8aq0y6mrtwqtwffp6t9a8fu0pdar6yerwzq6sr4m6ppk880gwqypxy6k
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2U2krNWNmaXY3MWozclZ0
            NHU2NDZWeS9UdEhDOXZGdzQ4WTNLT3p4Tm5ZCkRNNDZ5M0ZpM1NGcS9NUE1aaUM2
            R1J0R0VORk9LcXpkU1dHc2RNN25ucnMKLS0tIDJpOE5vRHpObGpHaEpnYml6MTdh
            aGVoSzhsVE5WYWZHQVc2eXRGcHdDejQKpFjAWAE9GG9mAJs0d+R+7q8aK7cMnvr4
            TJEiQvXjtfQv6tCyLXZuCfo5Jr40sc5J94cDvweiQ3BuoizqWOg11A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1850lrhfzq39frupln50mgqwxhgzlv78kzmgwxadk0wszxgxlhausq86luv
    lastmodified: "2026-07-22T03:20:28Z"
    mac: ENC[AES256_GCM,data:93RqtDLl+ov0roXLHqIqjoxPADaFL8iwpCYJCLJSgA72AGzWd+yReSAkbZPEiHnuQtQ6cjIZ/FpxVnA1jHa0b+Ga9CF8sAdUqv81xD3b5T13Qu8xSWyqfz/PugrZz+EIt9Ju2CRhuBV6UEXxvtVWFVhGLEHybJF1LRj2g0cmctc=,iv:z3UyfEZDnrXYnU0e7GUK+MfnDWBDNyZWALYYCCNofKY=,tag:34TfOTx+nBFr3wlQO18+ow==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
