borg-passphrase: ENC[AES256_GCM,data:F/nb/Oi6wnOLQUxKcFJKgKmAVeKGFBPRkobYQgXnzRxlm7/3LcTkv5VXFSQ=,iv:AbZwZ9hJRqJnw0C0aSLq2iYmieuFdnQQbDTfbPZnrS0=,tag:yAlyKc5OmJ8aL9XBnovdmg==,type:str]
borg-repo-env: ENC[AES256_GCM,data:EapCZkKnNcdL+CIGhKKQhmfxIqMu3NpeItyfp/Tr8HujlGtKweErnAvM/sXx70MSrNYXI2x4zwhn4A==,iv:BH3Bi5a83vb7TXw9drhZTNSqifXfbFOVm3BTxxel0Hc=,tag:2bvUh7Unuokp/1fU7DXZzQ==,type:str]
llama-swap-env: ENC[AES256_GCM,data:ee+hA2f12UTfA5YOT+lgFQ1GM/q0w5t0LNZOB+IUPBNe+n+UmlstaSSRFPnRc+5wHiPLov4MSM/mUHj00NSsCXSpeOcFRmMLy53qcXVwFgCPgKCnM3A=,iv:hALG665b5mxSokACRBH+nIUXM1s+U1EBX0CflFXm7MI=,tag:WLrdxS35IJ6G6y6LsJ6cug==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlSU1aSTNNblloRVFCM0ZK
            NGc0M0RYdkliaTRhRm5sZzlmUFdaYnV5K0UwClFjeGQyZmJ5WnE3YzNsWUpQOHlh
            cWo1NUdHWHQ2MVVLanUrSjNzditXTkkKLS0tIG11T1JnOEo5UlQ1MUIrcXZJS1Jm
            ZTRlblVteWRZK1E2bjdScGI2RDlhOVEKmNG50SllycTdt1pnqIKCiW8fI5xYIAdW
            Mydc0Se1sV4kO3GF+YhSDsH79/5QucQnPn85zXJyFzKnvqfQd9FCYA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17r8aq0y6mrtwqtwffp6t9a8fu0pdar6yerwzq6sr4m6ppk880gwqypxy6k
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2U2krNWNmaXY3MWozclZ0
            NHU2NDZWeS9UdEhDOXZGdzQ4WTNLT3p4Tm5ZCkRNNDZ5M0ZpM1NGcS9NUE1aaUM2
            R1J0R0VORk9LcXpkU1dHc2RNN25ucnMKLS0tIDJpOE5vRHpObGpHaEpnYml6MTdh
            aGVoSzhsVE5WYWZHQVc2eXRGcHdDejQKpFjAWAE9GG9mAJs0d+R+7q8aK7cMnvr4
            TJEiQvXjtfQv6tCyLXZuCfo5Jr40sc5J94cDvweiQ3BuoizqWOg11A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1850lrhfzq39frupln50mgqwxhgzlv78kzmgwxadk0wszxgxlhausq86luv
    lastmodified: "2026-07-23T03:35:12Z"
    mac: ENC[AES256_GCM,data:YtyVlx1UZdAdwEEsUwC1qmD7s6lPKwlOiCoh69cQr/WEu7VzhA+La4LmVi4FrLo7bwYvbm+GjUc5OB79DtO1q83+LyYQwdwqm/J3Ldcx9/ShOmmXpIvr6M8zsI1RYIEPLS1hYJTjX6CoBNV8m0041m0E4rIM7xmqMb6B6/TrMZs=,iv:z1PMb5Ob01G7Dbc44kkWO0JkrrC7FNqfp3ms8KucVQo=,tag:C6K6UtoJ/u9Q0o6PPUDLoA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
