# Disko layout for arquitens's 2TB Samsung 990 Pro — INTERIM (pre-SATA) form.
#
# Endgame is Ceph on a dedicated enterprise SATA SSD with PLP; those aren't here
# yet, so Ceph rides the NVMe for now. To make that later migration a pure online
# LVM op (no repartition, no reinstall), the interim OSD lives on a RAW LOGICAL
# VOLUME inside the VG rather than its own GPT partition:
#
#   GPT: ESP (1G) + LUKS (rest)
#        LUKS -> LVM VG "vg" -> { btrfs "pool", xfs "data", raw "ceph" }
#
#   - btrfs "pool" (400G): impermanence root + nix/persist/large/cache/dots.
#   - xfs   "data" (400G): /data — etcd + postgres + VM + local-path PVs (no CoW,
#                          flat fsync latency; k3s persistence points here).
#   - raw   "ceph" (768G): rook consumes /dev/vg/ceph directly as a BlueStore OSD.
#                          It sits INSIDE the host LUKS, so set rook
#                          `encryptedDevice: false` (don't double-encrypt).
#   - ~294G unallocated VG extents: dynamic over-provisioning + growth reserve.
#     (No bare OP partition needed — an LV layout reclaims via lvremove, and this
#     slack is never written so it stays in the SSD's free pool.)
#
# When the PLP SATA SSD arrives, migrate the OSD (add SATA OSD -> `ceph osd out`
# the NVMe one -> purge), then reclaim with NO repartition/reinstall:
#     ceph-volume lvm zap /dev/vg/ceph --destroy   # or: lvremove /dev/vg/ceph
#     lvextend -l +100%FREE /dev/vg/data && xfs_growfs /data
# ...and drop the `ceph` lv from this file to keep it honest.
#
# Mint (drive is new out of box, so no blkdiscard needed):
#     disko-install --flake .#arquitens --disk main /dev/disk/by-id/<990pro>
{ ... }:
let
  # Same btrfs options every other host uses.
  btrfsOpts = [
    "compress=zstd"
    "noatime"
  ];
  subvol = mountpoint: {
    inherit mountpoint;
    mountOptions = btrfsOpts;
  };
in
{
  disko.devices = {
    disk.main = {
      type = "disk";
      # Minting via a USB->NVMe bridge on the workstation, so this is the drive's
      # ATA-through-bridge by-id (real serial S7YCNJ0Y615193Y). Once it's internal
      # in arquitens the same serial appears as nvme-...S7YCNJ0Y615193Y; update this
      # only if you ever re-run `disko` on arquitens itself. Runtime is unaffected
      # either way — fileSystems are generated by partlabel.
      device = "/dev/disk/by-id/ata-Samsung_SSD_9100_PRO_2TB_S7YCNJ0Y615193Y";
      content = {
        type = "gpt";
        partitions = {
          ESP = {
            priority = 1;
            name = "ESP";
            size = "1G";
            type = "EF00";
            content = {
              type = "filesystem";
              format = "vfat";
              mountpoint = "/boot";
              mountOptions = [
                "fmask=0022"
                "dmask=0022"
              ];
            };
          };

          # Everything else -> LUKS -> LVM. 100% so it absorbs the whole remainder;
          # the LVs below are fixed-size, so the slack lands as unallocated VG
          # extents (over-provisioning + online-growth reserve).
          luks = {
            priority = 2;
            name = "luks";
            size = "100%";
            content = {
              type = "luks";
              # Unique mapper name (NOT "luks") so `cryptsetup open` doesn't
              # collide with the minting workstation's own /dev/mapper/luks — same
              # reason the liveusb uses "cryptliveusb". Runtime-only alias; the VG
              # PV, /dev/vg/* LVs and rollbackDevice are all unaffected.
              name = "cryptarquitens"; # -> /dev/mapper/cryptarquitens
              settings = {
                # TRIM through LUKS so fstrim + lvremove discards reach the SSD.
                allowDiscards = true;
                # Ceph shares this crypt path during the interim, so skip the
                # dm-crypt worker threads and encrypt inline — lower, flatter
                # latency for the OSD (and etcd/DB) at a small CPU cost. Safe on
                # a modern AES-NI CPU.
                bypassWorkqueues = true;
              };
              content = {
                type = "lvm_pv";
                vg = "vg";
              };
            };
          };
        };
      };
    };

    lvm_vg.vg = {
      type = "lvm_vg";
      lvs = {
        # btrfs pool: the impermanence subvolumes. Grows online into the VG
        # reserve via `lvextend -L +NG /dev/vg/pool && btrfs fi resize max /`.
        pool = {
          size = "400G";
          content = {
            type = "btrfs";
            extraArgs = [ "-f" ];
            mountpoint = "/mnt/btrfs_root";
            mountOptions = btrfsOpts;
            subvolumes = {
              "/root" = subvol "/";
              "/nix" = subvol "/nix";
              "/persist" = subvol "/persist";
              "/large" = subvol "/large";
              "/cache" = subvol "/cache";
              "/dots" = subvol "/dots";
            };
          };
        };

        # XFS data volume: etcd + DB + local-path PVs. Grows online via
        # `lvextend -L +NG /dev/vg/data && xfs_growfs /data` (XFS is grow-only).
        data = {
          size = "400G";
          content = {
            type = "filesystem";
            format = "xfs";
            mountpoint = "/data";
            mountOptions = [ "noatime" ];
          };
        };

        # Raw interim Ceph OSD — no content, so disko creates the LV but never
        # formats it. rook claims /dev/vg/ceph directly. Deleted (lvremove) once
        # the OSD migrates to the PLP SATA SSD; its extents return to the VG.
        ceph = {
          size = "768G";
        };
      };
    };
  };

  # The btrfs pool now lives on the LVM LV, NOT directly on /dev/mapper/luks, so
  # point the initrd rollback service at the LV. (Default is /dev/mapper/luks,
  # which is now an LVM PV — mounting it as btrfs would fail.)
  modules.system.impermanence.rollbackDevice = "/dev/vg/pool";

  # neededForBoot parity: impermanence binds these out of the persist subvols in
  # early boot, so they must be mounted in initrd. disko emits the fileSystems
  # entries; these assignments just add the flag (they merge).
  fileSystems = {
    "/mnt/btrfs_root".neededForBoot = true;
    "/nix".neededForBoot = true;
    "/persist".neededForBoot = true;
    "/large".neededForBoot = true;
    "/cache".neededForBoot = true;
    "/dots".neededForBoot = true;

    # k3s persists here (impermanence), which requires the root be mounted in
    # initrd. LVM is already activated early for the btrfs pool LV; this just
    # adds the XFS mount (module pulled in via supportedFilesystems below).
    "/data".neededForBoot = true;

    # Preserved from the old layout — not disko-managed.
    "/mnt/net-k8s" = {
      device = "recusant:/export/k8s";
      fsType = "nfs";
    };
  };

  # XFS /data is neededForBoot, so initrd must be able to mount it.
  boot.initrd.supportedFilesystems = [ "xfs" ];

  # Weekly fstrim so freed blocks (post lvremove/delete) return to the SSD's free
  # pool, sustaining dynamic over-provisioning alongside the VG reserve.
  services.fstrim.enable = true;
}
