# 1Password browser integration feature for Firefox-based browsers
{ config, lib, ... }:
{
  imports = [ ../app-spec.nix ];

  config.app = {
    nixpakModules = [
      (
        { lib, sloth, ... }:
        {
          bubblewrap = {
            # Allow execution of the 1Password BrowserSupport wrapper
            bind.ro = [
              "/run/wrappers/bin/1Password-BrowserSupport"
            ];

            # Native messaging hosts directory (Firefox-based browsers)
            # The actual manifest is generated by 1Password when extension connects
            bind.rw = [
              (sloth.concat' sloth.homeDir "/.mozilla/native-messaging-hosts")
              # 1Password socket for browser extension communication
              (sloth.concat' sloth.runtimeDir "/1Password-BrowserSupport.sock")
            ];
          };
        }
      )
    ];

    # Persist the native messaging manifest so it survives reboots
    persistence.user.persist = [
      ".mozilla/native-messaging-hosts"
    ];
  };
}
