# Global sandbox settings shared across all mkApp instances.
#
# The per-app backend/storage options live on modules.apps.<name>.sandbox.*
# (generated by lib/apps.nix). This module holds the fleet-wide knobs, the shared
# /<tier>/sandbox parent directories, the polkit rule for the systemd-stash
# backend, and the one-time data migration into the stash layout.
{
  config,
  lib,
  pkgs,
  ...
}:
let
  cfg = config.modules.sandbox;

  # Exact allowlist of the REAL sandbox-<app>.service units, for the polkit rule
  # below. A prefix match ("sandbox-*") was a root-escalation: manage-units also
  # gates StartTransientUnit, so jrt could `systemd-run --unit=sandbox-evil
  # --uid=0 -- …` and run arbitrary root commands. Only exact existing unit names
  # may be managed; a transient unit can't reuse a static unit's fragment name,
  # so this closes the hole.
  sandboxUnits = lib.filter (lib.hasPrefix "sandbox-") (lib.attrNames config.systemd.services);
  allowedUnitsJson = builtins.toJSON (map (u: "${u}.service") sandboxUnits);

  tierMount = {
    persist = "/persist";
    large = "/large";
    cache = "/cache";
  };

  co = "${pkgs.coreutils}/bin";
  ul = "${pkgs.util-linux}/bin";
  pg = "${pkgs.procps}/bin/pgrep";

  # Per-app migration from the old /<tier>/home/<user>/<path> impermanence layout
  # into /<tier>/sandbox/<app>/<path>. Runs from an activation script, so it fires
  # on `nixos-rebuild switch` (no reboot) AND on boot. Safe on a live system:
  #   - fully idempotent PER ENTRY (no app-level stamp), so a storage entry ADDED
  #     to an already-converted app migrates on the next switch — move only fires
  #     when the source exists and the target is absent/empty;
  #   - if the app is running it DEFERS (don't move data out from under it);
  #   - stale old-layout bind mounts (present after a switch, absent at boot) are
  #     unmounted deepest-first before the move;
  #   - both paths are on the same tier subvol, so `mv` is an atomic rename;
  #   - chowns reconcile ownership (handles same-uid <-> dedicated transitions).
  migrateApp =
    m:
    let
      unmounts = lib.concatMapStringsSep "\n" (
        e:
        let
          t = "/home/${m.user}/${e.path}";
        in
        ''
          if ${ul}/mountpoint -q "${t}" 2>/dev/null; then
            ${ul}/umount "${t}" 2>/dev/null || ${ul}/umount -l "${t}" 2>/dev/null || true
          fi''
      ) (lib.reverseList m.entries); # deepest-first
      moves = lib.concatMapStringsSep "\n" (
        e:
        let
          dst = "${tierMount.${e.tier}}/sandbox/${m.app}/${e.path}";
          # Old-layout data can sit under ANY tier's home: a path being re-tiered
          # (e.g. .claude/security persist→large, or codex logs persist→large) still
          # lives under the parent's OLD tier, not its new declared one. Search the
          # declared tier first, then the others; take the first that exists. Each
          # candidate test is fully quoted, so paths with spaces (Electron's
          # "Code Cache") are safe.
          candidateTiers = [ e.tier ] ++ (lib.filter (t: t != e.tier) [ "persist" "large" "cache" ]);
          srcPick = lib.concatMapStringsSep "\n" (
            t:
            let
              c = "${tierMount.${t}}/home/${m.user}/${e.path}";
            in
            ''            if [ -z "$__src" ] && [ -e "${c}" ]; then __src="${c}"; fi''
          ) candidateTiers;
        in
        ''
          __src=""
          ${srcPick}
          if [ -n "$__src" ]; then
            ${co}/mkdir -p "$(${co}/dirname "${dst}")"
            if [ ! -e "${dst}" ]; then
              echo "  mv ${dst}"; ${co}/mv "$__src" "${dst}" || echo "  ERROR moving $__src"
            elif [ -d "${dst}" ] && [ -z "$(${co}/ls -A "${dst}" 2>/dev/null)" ]; then
              ${co}/rmdir "${dst}"; echo "  mv(empty) ${dst}"; ${co}/mv "$__src" "${dst}" || echo "  ERROR moving $__src"
            else
              echo "  skip ${e.path} (target non-empty)"
            fi
          fi${lib.optionalString (e.tier == "cache") ''

          # Cache is disposable: after migrating the canonical copy, delete any
          # stale duplicates of this EXACT declared path left under the other tiers
          # (the persist/cache desync), so the persist parent move can't sweep them
          # into the backed-up stash. Bounded to declared cache entries only.
          ${lib.concatMapStringsSep "\n" (
            t:
            let
              c = "${tierMount.${t}}/home/${m.user}/${e.path}";
            in
            ''          if [ -e "${c}" ]; then echo "  rm stale cache ${c}"; ${co}/rm -rf "${c}"; fi''
          ) candidateTiers}''}''
      ) (lib.reverseList m.entries); # deepest-first: extract carved children before the parent moves
      # Reconcile ownership every run (not gated by the stamp): mv preserves the
      # old jrt ownership, and flipping an app same-uid <-> dedicated changes the
      # target owner. chown-on-mismatch is cheap and idempotent.
      chowns = lib.concatMapStringsSep "\n" (
        e:
        let
          dst = "${tierMount.${e.tier}}/sandbox/${m.app}/${e.path}";
        in
        ''
          if [ -e "${dst}" ]; then
            __cur=$(${co}/stat -c %U "${dst}" 2>/dev/null || echo "")
            if [ "$__cur" != "${m.owner}" ]; then
              echo "  chown ${m.owner} ${dst}"; ${co}/chown -R "${m.owner}" "${dst}" 2>/dev/null || true
            fi
          fi''
      ) m.entries;
    in
    ''
      if ${pg} -x "${m.bin}" >/dev/null 2>&1; then
        : # ${m.app} running — defer; retries next switch/boot
      else
        ${unmounts}
        ${moves}
        ${chowns}
      fi
    '';

  migrateScript = pkgs.writeShellScript "sandbox-stash-migrate" ''
    ${lib.concatMapStringsSep "\n" migrateApp cfg.stashMigrations}
    exit 0
  '';
in
{
  options.modules.sandbox = {
    forceHomeLocation = lib.mkOption {
      type = lib.types.bool;
      default = false;
      description = ''
        Force every app.storage entry across ALL apps to location = "home"
        (data at the normal ~/<path> via impermanence, host-visible), overriding
        per-entry placement and the hidden stash. One switch for debugging,
        inspection, recovery, or a host where hiding isn't wanted. Sandboxing
        itself is unaffected — only the stash placement is disabled.
      '';
    };

    stashMigrations = lib.mkOption {
      internal = true;
      default = [ ];
      type = lib.types.listOf (
        lib.types.submodule {
          options = {
            app = lib.mkOption { type = lib.types.str; };
            bin = lib.mkOption { type = lib.types.str; };
            user = lib.mkOption { type = lib.types.str; }; # old-layout source user
            owner = lib.mkOption { type = lib.types.str; }; # target stash ownership
            entries = lib.mkOption {
              type = lib.types.listOf (
                lib.types.submodule {
                  options = {
                    tier = lib.mkOption { type = lib.types.str; };
                    path = lib.mkOption { type = lib.types.str; };
                  };
                }
              );
            };
          };
        }
      );
      description = ''
        Internal aggregation (set by the stash backends): per-app stash entries
        whose existing data must be moved once from the old
        /<tier>/home/<user>/<path> impermanence layout into
        /<tier>/sandbox/<app>/<path>. Consumed by the migration activation script.
      '';
    };
  };

  config = {
    # Shared parents of the per-app stashes. Traversable (0711) but NOT itself a
    # lock: the per-app lock lives on /<tier>/sandbox/<app> (see lib/storage.nix).
    # Locking these 0700 root would deny jrt the search bit and break every
    # rootless-nixpak app trying to reach its own stash.
    systemd.tmpfiles.rules = [
      "d /persist/sandbox 0711 root root -"
      "d /large/sandbox   0711 root root -"
      "d /cache/sandbox   0711 root root -"
    ];

    # The systemd-stash backend runs each app as a root-set-up system service
    # (private mount ns + stash graft, then drop to the user). The user triggers
    # it with `systemctl start --wait sandbox-<app>` and stops it on teardown, so
    # allow the desktop user to manage ONLY the exact set of generated
    # sandbox-<app>.service units. NOT a prefix match: manage-units also gates
    # StartTransientUnit, so `sandbox-*` would let jrt systemd-run an arbitrary
    # root unit named "sandbox-…". The exact allowlist is what closes that hole.
    #
    # Verb-pinning (start/stop only) was tried as extra defense-in-depth, but the
    # launcher's `start --wait` path did NOT present verb=="start" to this rule
    # (it fell through to an auth prompt), so it's dropped — the name allowlist is
    # the real control and a transient unit can't reuse a static fragment name.
    security.polkit.extraConfig = ''
      polkit.addRule(function(action, subject) {
        if (action.id == "org.freedesktop.systemd1.manage-units" &&
            subject.user == "jrt") {
          var allowed = ${allowedUnitsJson};
          var unit = action.lookup("unit");
          if (unit && allowed.indexOf(unit) >= 0) {
            return polkit.Result.YES;
          }
        }
      });
    '';

    # Cross-uid document portal: our xdg-desktop-portal fork mounts the
    # document-portal FUSE with allow_other (overlays/custom-packages.nix) so a
    # dedicated-uid app can read the doc:// files jrt's portal exports. fusermount3
    # refuses an allow_other mount unless user_allow_other is set here — and if the
    # mount is refused the portal fails to start, breaking file dialogs for EVERY
    # sandboxed app, so this and the overlay change are a matched pair.
    programs.fuse.userAllowOther = true;

    # One-time data migration into the stash layout. As an activation script it
    # runs on `nixos-rebuild switch` (no reboot needed) and on boot, before the
    # graphical session — see migrateApp above for the safety properties.
    system.activationScripts.sandbox-stash-migrate = lib.mkIf (cfg.stashMigrations != [ ]) {
      text = "${migrateScript}";
      deps = [ ];
    };
  };
}
