# Global sandbox settings shared across all mkApp instances.
#
# The per-app backend/storage options live on modules.apps.<name>.sandbox.*
# (generated by lib/apps.nix). This module holds the fleet-wide knobs and the
# shared /<tier>/sandbox parent directories that every per-app stash nests under.
{ config, lib, ... }:
{
  options.modules.sandbox = {
    forceHomeLocation = lib.mkOption {
      type = lib.types.bool;
      default = false;
      description = ''
        Force every app.storage entry across ALL apps to location = "home"
        (data at the normal ~/<path> via impermanence, host-visible), overriding
        per-entry placement and the hidden stash. One switch for debugging,
        inspection, recovery, or a host where hiding isn't wanted. Sandboxing
        itself is unaffected — only the stash placement is disabled.
      '';
    };
  };

  config = {
    # Shared parents of the per-app stashes. Traversable (0711) but NOT itself a
    # lock: the per-app lock lives on /<tier>/sandbox/<app> (see lib/storage.nix).
    # Locking these 0700 root would deny jrt the search bit and break every
    # rootless-nixpak app trying to reach its own stash.
    systemd.tmpfiles.rules = [
      "d /persist/sandbox 0711 root root -"
      "d /large/sandbox   0711 root root -"
      "d /cache/sandbox   0711 root root -"
    ];
  };
}
